spring:
  application:
    name: zuuldemo

server:
  port: 8080
okta:
  oauth2:
    issuer: https://dev-770454.okta.com/oauth2/default
    client-id: 0oa2amci5xaQcrWbF357
    client-secret: Q4td2nLNaZAJIZOcqmgBh-_BdEnC0sbw_a5b84HV

zuul:
  routes:
    demo-service:
      path: /api/**
      strip-prefix: true
      service-id: DEMOSERVICE

    ui:
      path: /**
      url: http://localhost:4200

logging:
  level:
    org:
      springframework:
        cloud:
          netflix: trace
        security: trace
